### PR TITLE
Expand error message when geolocation or band data is missing

### PR DESCRIPTION
**Pull request by tparker-usgs**
Clarify exception message when either geoloc or band data is missing.

### CODE REVIEW

**Comment by davidh-ssec** [comment]
@mraspaud What's your opinion on this? The changes make sense to me assuming the string formatting works as is with `"%d" % x + "another string"`. Do we want to be making changes to mpop still that aren't necessarily bug fixes?

**Comment by tparker-usgs** [comment]
I'm not too attached to this pull request, but do think it addresses a bug. The "Not all geo location files for this scene are present" message caused some confusion  before I discovered that it wasn't really a missing geo loc file that was triggering it. Misleading error messages can be confounding.

Is there a more pythonic way of handling the strings? I struggled a bit keeping the lines short while working 6 indentations deep.

**Comment by davidh-ssec** [comment]
Agreed your changes are helpful. As for string formatting it depends. Python is currently in a state of having 3 methods for formatting strings also mpop typically follows the 80 character line limit iirc, so it's understandable that it was difficult. My worry was that `"%d" % x + "other string"` would try to add the `x + "other string"` before formatting the string. One option could have been to try to combine all the strings then do the formatting with `("a" + "%d" + "c") % (x,)`. There is also `"a {:d} c".format(x)` which is probably more accepted as python 2 goes away.

**Comment by mraspaud** [comment]
Then concatenation seems to work as is, so I'm merging this:
```In [2]: x = 5

In [3]: "%d" % x + "another string"
Out[3]: '5another string'
```

**Pull request merged**
