### PR TITLE
Added LAC AVHRR satin drivers for CLASS L1B data

### PR DESCRIPTION
**Pull request by spareeth**
Added LAC AVHRR (both KLM and POD) satin drivers for CLASS L1B data and also for the GAC data from NOAA CLASS from NOAA14..

### CODE REVIEW

**Comment by mraspaud** [comment]
Thanks for the new functionalities, @spareeth !
Just a question: why do you reimplement the KLMReader and PODReader that are already implemented in pygac ?

**Comment by spareeth** [comment]
Hi
On Fri, Jan 23, 2015 at 11:07 AM, Martin Raspaud <notifications@github.com>
wrote:

> Thanks for the new functionalities, @spareeth
> <https://github.com/spareeth> !
> Just a question: why do you reimplement the KLMReader and PODReader that
> are already implemented in pygac ?
>
That's a good question.  May be when I started I tried to bring everything
to mpop to work it as stand alone satin driver, with out depending on pygac.

Anyway, still it will not work with out pygac installed.

**Comment by mraspaud** [comment]
Yes, pygac would be needed indeed, but I don't think that's a problem at all. I'd rather have pygac as a dependency than having to maintain the same code in two places.

**Comment by mraspaud** [comment]
Modified and merge into pre-master. Thanks @spareeth !

**Pull request closed without merging**
